import type { Locale } from "../i18n";
const en = { crop: "Crop canvas", apply: "Apply", cancel: "Cancel", snap: "Snap to canvas", align: "Align layers", left: "Left", center: "Horizontal center", right: "Right", top: "Top", middle: "Vertical center", bottom: "Bottom", horizontal: "Distribute horizontally", vertical: "Distribute vertically", mask: "Linked mask", owner: "Mask for", preview: "Export preview", previewFailed: "Preview unavailable", lockRatio: "Lock aspect ratio", size: "Encoded size", effects: "Layer effects", shadow: "Drop shadow", outline: "Stroke", color: "Color", radius: "Blur", width: "Width", opacity: "Opacity", busy: "Restoring history…" };
type Copy = typeof en;
export const editingCopy: Record<Locale, Copy> = {
 en,
 "zh-CN": { crop: "裁剪画布", apply: "应用", cancel: "取消", snap: "吸附画布", align: "图层对齐", left: "左对齐", center: "水平居中", right: "右对齐", top: "顶部对齐", middle: "垂直居中", bottom: "底部对齐", horizontal: "水平等距分布", vertical: "垂直等距分布", mask: "关联蒙版", owner: "所属图层", preview: "导出预览", previewFailed: "无法生成预览", lockRatio: "锁定宽高比", size: "编码大小", effects: "图层效果", shadow: "投影", outline: "描边", color: "颜色", radius: "模糊", width: "宽度", opacity: "不透明度", busy: "正在恢复历史…" },
 "zh-TW": { crop: "裁剪畫布", apply: "套用", cancel: "取消", snap: "吸附畫布", align: "圖層對齊", left: "靠左對齊", center: "水平置中", right: "靠右對齊", top: "頂部對齊", middle: "垂直置中", bottom: "底部對齊", horizontal: "水平等距分布", vertical: "垂直等距分布", mask: "關聯遮罩", owner: "所屬圖層", preview: "匯出預覽", previewFailed: "無法產生預覽", lockRatio: "鎖定寬高比", size: "編碼大小", effects: "圖層效果", shadow: "投影", outline: "描邊", color: "顏色", radius: "模糊", width: "寬度", opacity: "不透明度", busy: "正在恢復歷史…" },
 ja: { crop: "キャンバスを切り抜く", apply: "適用", cancel: "キャンセル", snap: "キャンバスにスナップ", align: "レイヤーを整列", left: "左揃え", center: "水平方向中央揃え", right: "右揃え", top: "上揃え", middle: "垂直方向中央揃え", bottom: "下揃え", horizontal: "水平方向に等間隔", vertical: "垂直方向に等間隔", mask: "リンクされたマスク", owner: "対象レイヤー", preview: "書き出しプレビュー", previewFailed: "プレビューを生成できません", lockRatio: "縦横比を固定", size: "エンコードサイズ", effects: "レイヤー効果", shadow: "ドロップシャドウ", outline: "境界線", color: "色", radius: "ぼかし", width: "幅", opacity: "不透明度", busy: "履歴を復元中…" },
};
