const en = {
  menuBar: "Application menu", file: "File", edit: "Edit", view: "View",
  import: "Import", importImage: "Image (PNG, JPG)", importOpenRaster: "OpenRaster (.ora)", export: "Export", projects: "Open saved project", noProjects: "No saved projects", new: "New project",
  rename: "Rename", invalidName: "Use a name of 1–160 characters.", settings: "Settings",
  clearLocalCache: "Clear local render cache",
  localCacheChecking: "Local render cache: checking…", localCacheUnavailable: "Local render cache: unavailable", localCacheMemory: "Local render cache: {size} KiB · memory only", localCachePersistent: "Local render cache: {size} KiB · persistent",
  copy: "Copy", cut: "Cut", paste: "Paste", undo: "Undo", redo: "Redo", duplicateLayer: "Duplicate layer", deleteLayer: "Delete layer",
  zoomOut: "Zoom out", zoomIn: "Zoom in", actualSize: "Actual size (100%)", fit: "Fit canvas", navigator: "Navigator",
  shortcuts: "Keyboard shortcuts", shortcutHint: "Click a shortcut and press a letter or number, optionally with Ctrl/⌘ and Shift. Shortcuts apply while the canvas has focus. Settings are saved in this browser.",
  clear: "Clear", defaults: "Restore defaults", save: "Save", cancel: "Cancel",
  invalidKey: "This key is reserved or unsupported.", conflict: "This shortcut is already assigned.", storageFailed: "Settings could not be saved in this browser.",
  oraHint: "OpenRaster keeps editable layers in Image Studio. Adjustment effects and transformed groups use rendered fallback layers in other editors.",
  failed: "The file could not be processed. Check its format, size and supported layer features.", busy: "Processing file…",
  discard: "This project has unsaved changes. Save it or export OpenRaster before switching. Continue without saving?",
  legacy: "Legacy project (.json)", close: "Close",
  apiKey: "API Key", apiKeyTitle: "skillsmaster.jp API Key", apiKeyHint: "Image Studio sends AI edits to {baseUrl} with this key. The key is stored only on this Image Studio server and is never shown again in the browser.",
  apiKeyInput: "API key", apiKeyPlaceholder: "Paste the key issued by skillsmaster.jp", apiKeyStatus: "Current key", apiKeyNone: "Not configured", apiKeySet: "Saved ({hint})",
  apiKeyManaged: "Set by the server configuration file ({hint}). Change it there.", apiKeyDisabled: "AI is disabled for this installation.", apiKeyLoading: "Loading…",
  apiKeySaved: "API key saved and verified.", apiKeyUnverified: "API key saved, but it could not be verified now.", apiKeyRemove: "Remove key", apiKeyRemoved: "API key removed.", apiKeyFailed: "The API key could not be saved.",
};

export type FileCopy = { [Key in keyof typeof en]: string };

export const fileCopy: Record<"en" | "ja" | "zh-CN" | "zh-TW", FileCopy> = {
  en,
  ja: {
    menuBar: "アプリケーションメニュー", file: "ファイル", edit: "編集", view: "表示",
    import: "読み込み", importImage: "画像（PNG、JPG）", importOpenRaster: "OpenRaster（.ora）", export: "書き出し", projects: "保存済みプロジェクトを開く", noProjects: "保存済みプロジェクトはありません", new: "新規プロジェクト",
    rename: "名前を変更", invalidName: "名前は1〜160文字で入力してください。", settings: "設定",
    clearLocalCache: "ローカル描画キャッシュを消去",
    localCacheChecking: "ローカル描画キャッシュ: 確認中…", localCacheUnavailable: "ローカル描画キャッシュ: 利用不可", localCacheMemory: "ローカル描画キャッシュ: {size} KiB · メモリのみ", localCachePersistent: "ローカル描画キャッシュ: {size} KiB · 永続化",
    copy: "コピー", cut: "切り取り", paste: "貼り付け", undo: "元に戻す", redo: "やり直す", duplicateLayer: "レイヤーを複製", deleteLayer: "レイヤーを削除",
    zoomOut: "縮小", zoomIn: "拡大", actualSize: "100%表示", fit: "全体表示", navigator: "ナビゲーター",
    shortcuts: "キーボードショートカット", shortcutHint: "項目を選び、英数字キーと任意のCtrl/⌘・Shiftを押してください。キャンバスにフォーカスがある時に有効です。設定はこのブラウザーに保存されます。",
    clear: "解除", defaults: "初期設定に戻す", save: "保存", cancel: "キャンセル",
    invalidKey: "このキーは予約済み、または未対応です。", conflict: "このショートカットは使用中です。", storageFailed: "このブラウザーに設定を保存できませんでした。",
    oraHint: "OpenRasterはImage Studioの編集可能なレイヤーを保持します。他のエディターでは調整効果と変形グループを画像として表示します。",
    failed: "ファイルを処理できませんでした。形式、サイズ、対応レイヤーを確認してください。", busy: "ファイルを処理中…",
    discard: "未保存の変更があります。切り替える前に保存するかOpenRasterを書き出してください。保存せずに続けますか？",
    legacy: "旧プロジェクト (.json)", close: "閉じる",
    apiKey: "API キー", apiKeyTitle: "skillsmaster.jp API キー", apiKeyHint: "AI編集はこのキーで {baseUrl} に送信されます。キーはこの Image Studio サーバーにのみ保存され、ブラウザーに再表示されることはありません。",
    apiKeyInput: "API キー", apiKeyPlaceholder: "skillsmaster.jp で発行されたキーを貼り付け", apiKeyStatus: "現在のキー", apiKeyNone: "未設定", apiKeySet: "保存済み（{hint}）",
    apiKeyManaged: "サーバー設定ファイルで指定されています（{hint}）。変更は設定ファイルで行ってください。", apiKeyDisabled: "このインストールでは AI が無効です。", apiKeyLoading: "読み込み中…",
    apiKeySaved: "API キーを保存し、確認しました。", apiKeyUnverified: "API キーを保存しましたが、現在は確認できませんでした。", apiKeyRemove: "キーを削除", apiKeyRemoved: "API キーを削除しました。", apiKeyFailed: "API キーを保存できませんでした。",
  },
  "zh-CN": {
    menuBar: "应用菜单", file: "文件", edit: "编辑", view: "视图",
    import: "导入", importImage: "图片（PNG、JPG）", importOpenRaster: "OpenRaster（.ora）", export: "导出", projects: "打开已保存项目", noProjects: "没有已保存项目", new: "新建项目",
    rename: "重命名", invalidName: "名称须为 1–160 个字符。", settings: "设置",
    clearLocalCache: "清除本地渲染缓存",
    localCacheChecking: "本地渲染缓存：正在检查…", localCacheUnavailable: "本地渲染缓存：不可用", localCacheMemory: "本地渲染缓存：{size} KiB · 仅内存", localCachePersistent: "本地渲染缓存：{size} KiB · 持久化",
    copy: "复制", cut: "剪切", paste: "粘贴", undo: "撤销", redo: "重做", duplicateLayer: "复制图层", deleteLayer: "删除图层",
    zoomOut: "缩小", zoomIn: "放大", actualSize: "实际大小（100%）", fit: "适合画布", navigator: "导航器",
    shortcuts: "快捷键设置", shortcutHint: "点击快捷键后按字母或数字，可组合 Ctrl/⌘ 和 Shift。快捷键仅在画布获得焦点时生效，设置保存在当前浏览器。",
    clear: "清除", defaults: "恢复默认", save: "保存", cancel: "取消",
    invalidKey: "该按键被保留或暂不支持。", conflict: "该快捷键已分配给其他操作。", storageFailed: "无法在当前浏览器保存设置。",
    oraHint: "OpenRaster 保留本站可编辑图层。在其他编辑器中，调整效果和变换后的图层组以渲染图层显示。",
    failed: "无法处理文件，请检查格式、大小和图层功能是否受支持。", busy: "正在处理文件…",
    discard: "项目存在未保存的修改。切换前请保存或导出 OpenRaster。仍要放弃未保存修改并继续吗？",
    legacy: "旧版项目 (.json)", close: "关闭",
    apiKey: "API Key", apiKeyTitle: "skillsmaster.jp API Key", apiKeyHint: "AI 编辑将使用此 Key 发送到 {baseUrl}。Key 只保存在本 Image Studio 服务器上，保存后不会再在浏览器中显示。",
    apiKeyInput: "API Key", apiKeyPlaceholder: "粘贴 skillsmaster.jp 签发的 Key", apiKeyStatus: "当前 Key", apiKeyNone: "未配置", apiKeySet: "已保存（{hint}）",
    apiKeyManaged: "由服务器配置文件指定（{hint}），请在配置文件中修改。", apiKeyDisabled: "此安装已禁用 AI。", apiKeyLoading: "加载中…",
    apiKeySaved: "API Key 已保存并验证通过。", apiKeyUnverified: "API Key 已保存，但暂时无法验证。", apiKeyRemove: "删除 Key", apiKeyRemoved: "API Key 已删除。", apiKeyFailed: "无法保存 API Key。",
  },
  "zh-TW": {
    menuBar: "應用程式選單", file: "檔案", edit: "編輯", view: "檢視",
    import: "匯入", importImage: "圖片（PNG、JPG）", importOpenRaster: "OpenRaster（.ora）", export: "匯出", projects: "開啟已儲存專案", noProjects: "沒有已儲存專案", new: "新增專案",
    rename: "重新命名", invalidName: "名稱須為 1–160 個字元。", settings: "設定",
    clearLocalCache: "清除本機渲染快取",
    localCacheChecking: "本機渲染快取：正在檢查…", localCacheUnavailable: "本機渲染快取：不可用", localCacheMemory: "本機渲染快取：{size} KiB · 僅記憶體", localCachePersistent: "本機渲染快取：{size} KiB · 持久化",
    copy: "複製", cut: "剪下", paste: "貼上", undo: "復原", redo: "重做", duplicateLayer: "複製圖層", deleteLayer: "刪除圖層",
    zoomOut: "縮小", zoomIn: "放大", actualSize: "實際大小（100%）", fit: "適合畫布", navigator: "導覽器",
    shortcuts: "快捷鍵設定", shortcutHint: "點擊快捷鍵後按英文字母鍵或數字，可組合 Ctrl/⌘ 和 Shift。快捷鍵僅在畫布取得焦點時生效，設定儲存在目前瀏覽器。",
    clear: "清除", defaults: "還原預設", save: "儲存", cancel: "取消",
    invalidKey: "此按鍵被保留或不支援。", conflict: "此快捷鍵已指派給其他操作。", storageFailed: "無法在目前瀏覽器儲存設定。",
    oraHint: "OpenRaster 保留本站可編輯圖層。在其他編輯器中，調整效果與變形後的圖層群組以影像圖層顯示。",
    failed: "無法處理檔案，請檢查格式、大小與圖層功能是否支援。", busy: "正在處理檔案…",
    discard: "專案有尚未儲存的修改。切換前請儲存或匯出 OpenRaster。仍要放棄未儲存修改並繼續嗎？",
    legacy: "舊版專案 (.json)", close: "關閉",
    apiKey: "API Key", apiKeyTitle: "skillsmaster.jp API Key", apiKeyHint: "AI 編輯將使用此 Key 傳送到 {baseUrl}。Key 只儲存在本 Image Studio 伺服器上，儲存後不會再於瀏覽器中顯示。",
    apiKeyInput: "API Key", apiKeyPlaceholder: "貼上 skillsmaster.jp 核發的 Key", apiKeyStatus: "目前 Key", apiKeyNone: "未設定", apiKeySet: "已儲存（{hint}）",
    apiKeyManaged: "由伺服器設定檔指定（{hint}），請在設定檔中修改。", apiKeyDisabled: "此安裝已停用 AI。", apiKeyLoading: "載入中…",
    apiKeySaved: "API Key 已儲存並驗證通過。", apiKeyUnverified: "API Key 已儲存，但暫時無法驗證。", apiKeyRemove: "刪除 Key", apiKeyRemoved: "API Key 已刪除。", apiKeyFailed: "無法儲存 API Key。",
  },
};
